### ISSUE TITLE
JDeferred 1.2.5 android not working

### ISSUE THREAD

**Issue by dalibor983** [jdeferred/jdeferred#101]
In android 1.2.5 version throws this error:
```
Dex cannot parse version 52 byte code
```

I think this happens because the source is compiled with java 1.8 target compatibility but I use 1.7 in my android application.

I cannot switch my project to 1.8 because that requires jack compiler to be enabled but jack compiler is currently has some issues with android data binding. Until this issues are resolved I cannot switch my project to 1.8.

Can we get build for java 1.7 available at some public maven repositories?

**Comment by aalmiray** [comment]
@saturnism I recommend releasing 1.2.6 asap as this and #97 affect Android users.
