### ISSUE TITLE
Updatable deferred

### ISSUE THREAD

**Issue by Gloix** [jdeferred/jdeferred#103]
I'm using a database that can push modifications to the client whenever data changes. It would be great to have a deferred object (or something alike) that can be resolved multiple times, in this case for every database update.

I found an Angular library that does this by adding `update()` and `mistake()` methods to deferreds.

DeferredWithUpdate.js
https://github.com/bennadel/DeferredWithUpdate.js

**Comment by aalmiray** [comment]
What about publishing intermediate results with `notify()` and registering a `ProgressCallback` on the promise?

**Comment by Gloix** [comment]
I guess that is a solution, but it's not enough for what I need. I have to join multiple sets of data that are queryed asynchronously and I can only show results to the user when data is finally joined. For that I use a DeferredManager instance that waits until all promises are done. BUT data can change after the compiled list is shown and since I cannot re-resolve deferreds I have to do some trickery

```
/* class instance variable */
private Set<String> allData = new HashSet<>();

/*class method*/
Set<DataLoader> dataLoaders = mDataLoaderFactory.getDataLoaders();
Set<Promise> promiseSet = new HashSet<>();
for(DataLoader dataLoader : dataLoaders) {
    final Deferred deferred = new DeferredObject();
    dataLoader.load(new OnDataLoadedListener() {
        String previouslyLoadedData;

        // This method can be called multiple times
        void onDataLoaded(String data) {
            if(previouslyLoadedData != null) {
                allData.remove(previouslyLoadedData);
            }
            previouslyLoadedData = data;
            allData.add(data);
            if(deferred.isResolved()) {  // Seems 'hacky'
                onAllDataLoaded();
            } else {
                deferred.resolve();
            }
        }
    })
    promiseSet.add(deferred);
}

// Do something when all data sources have reported something.
// Only possible when data sources resolve the promises (not update progress).
DeferredManager dm = new DefaultDeferredManager();
dm.when(promiseSet.toArray(new Promise[]{}))
        .done(new DoneCallback() {
                @Override
                public void onDone(Object result) {
                    onAllDataLoaded();
                }
        });


private void onAllDataLoaded() {
    /* show allData to the user */
}
```

If there's a more clever way of waiting for all loaders to report something and keep updating the data with new updates, please let me know.

PD: After writing this, I tried to do it by using a progress listener in the promise returned by DeferredManager's when method, but even there I have no _direct_ way of knowing if all sources have at least loaded once. I know that using a counter would be one way to go, but I think it goes against the spirit of a DeferredManager in which I can set something to be done when a series of other things are done.

**Comment by Gloix** [comment]
I recently discovered the world of reactive programming, which was what I needed, so I'll leave this closed.
