### ISSUE TITLE
Version 1.2.6 on maven central ?

### ISSUE THREAD

**Issue by aveuiller** [jdeferred/jdeferred#108]
Hello,

It would be nice to have access to this library on Android, do you plan to release the next snapshot soon?

Thanks. :)

**Comment by xin-zhang** [comment]
I'm hoping to see 1.2.6 coming out soon too.
Really would like to use it in my project.

**Comment by aveuiller** [comment]
For those interested, I uploaded the 1.2.6 artifact under another group id while waiting for the official release: https://search.maven.org/#search%7Cga%7C1%7Cio.apisense.jdeferred

**Comment by saturnism** [comment]
Hiya! apologies for the delay here. Thanx @aveuiller! I'll get this out soon :)

**Comment by Gerst20051** [comment]
thanks patiently waiting! @saturnism

**Comment by saturnism** [comment]
apologies for the delays. :) it's been pushed to bintray, and sync'ing w/ maven central.

**Comment by saturnism** [comment]
it should be there now, cheers!  @aveuiller thnx again for jumping in to help as well! really appreciate it.

**Comment by Gerst20051** [comment]
thanks @saturnism
