### ISSUE TITLE
Improve "Quick Examples" with more lambda showcase

### ISSUE THREAD

**Issue by sgwerder** [jdeferred/jdeferred#109]
Show a side-by-side comparison of lambda support in all "Quick Examples" viewable at http://jdeferred.org.

Or atleast highlight the lambda section by moving it up.

**Comment by saturnism** [comment]
hiya, please take a look at the PR. Thanks!

**Comment by saturnism** [comment]
hiya! moved the section up a bit. would love to get your input/PR on more examples.  Cheers!

**Comment by sgwerder** [comment]
I think it looks good.

**Comment by saturnism** [comment]
thnx!
