### ISSUE TITLE
With multiple results it is hard to access the cause of the failure

### ISSUE THREAD

**Issue by tbee** [jdeferred/jdeferred#113]
On normal calls, the fail method has the exception as the parameter. When syncing multiple calls, the fail method returns a OneReject instance. But it is not easy (if even possible) to access the exception causing the failure through that instance. 
https://github.com/jdeferred/jdeferred/blob/master/subprojects/jdeferred-core/src/main/java/org/jdeferred/multiple/OneReject.java

**Comment by saturnism** [comment]
Ah, it feels like OneReject should have the rejection type as a generic.
Would that help w better type safety?

**Comment by tbee** [comment]
This is not about type safety; I just want to know what caused the fail to be called. The 'normal' fail gets the causing exception as a parameter, where is it hidden here?

**Comment by saturnism** [comment]
Iirc, It should be in the OneReject.getReject()

But you do need to an instanceof and then casting it

**Comment by tbee** [comment]
Ok. I see. And I see that the other fail method also has a parameter of type Object. Isn't that always a Throwable or Exception?

**Comment by saturnism** [comment]
not quite, you can reject with a non-Exception. E.g., deferred.reject("failed")

However, if you let DeferredManager to create a promise from a Callable, then the rejection is always an Exception.

**Comment by tbee** [comment]
Ok! With the javascript roots I get that. I would have wrapped that reject in an exception so the API would be identical. Butthat explains it. Thanks.

**Comment by saturnism** [comment]
Sounds like we were good. Closing for now :) Thanks!
