### ISSUE TITLE
Improve code formatting, compiler warnings and JavaDoc

### ISSUE THREAD

**Issue by sclassen** [jdeferred/jdeferred#148]
I would like to contribute a series of PullRequests to 2.x branch fixing up some code formatting, compiler warning and JavaDoc improvements.

This issue should serve as a container to bundle the PullRequests and maybe to discuss issues which arise.

As the plan is to NOT change any logic/behaviour I would not put this issue on the 2.x roadmap.

**Comment by aalmiray** [comment]
thank you for having a look at this @sclassen 😁

**Comment by saturnism** [comment]
I think everything is merged, closing for now :D thnx @sclassen!
