### ISSUE TITLE
For JDeferred 2, update artifact and package names

### ISSUE THREAD

**Issue by saturnism** [jdeferred/jdeferred#156]
To avoid conflicts w/ widely used JDeferred 1.x, proposing to use different Maven coordinate and also Java package name.

E.g.,
Maven Artifact: `org.jdeferred:jdeferred-core2`
Java Package: `org.jdeferred.core2`
Java Module: `org.jdeferred.core2`

Or,
Maven Artifact: `org.jdeferred2:jdeferred-core`
Java Package: `org.jdeferred2.core`
Java Module: `org.jdeferred2.core`

Need to decide on a scheme.

**Comment by aalmiray** [comment]
Already working on it. There's one issue with the binary report though, changing the package will mark a coarse change (all classes change!) thus I'll compute it with the old package name first. The report will be added to the site 😄

**Comment by saturnism** [comment]
wow, magic!
