### ISSUE TITLE
Usage with network calls, errors swallowed

### ISSUE THREAD

**Issue by MaximusMcCann** [jdeferred/jdeferred#43]
Trying to have network calls run with jdeferred, but responses never seem to return and errors are swallowed. Is there a better way to do the below?  This is in an Android lib module, being tested on a junit module.  Side note: the lambdas work on Android using [Retrolambda](https://github.com/orfjackal/retrolambda)

Below uses org.apache.http (had an initial working version with futures from [Async-Http-Client](https://github.com/AsyncHttpClient/async-http-client), but Android said it was making network calls on the main thread)

```
private static final  Promise __getRequest(String url) {
       Deferred d = new DeferredObject();
        Promise p = d.promise();
        //AndroidDeferredManager adm = new AndroidDeferredManager();
        DeferredManager dm = new DefaultDeferredManager();

        final HttpParams httpParameters = new BasicHttpParams(); // Have also tried putting these in the lambda
        final HttpClient client = new DefaultHttpClient(httpParameters);
        final HttpGet method = new HttpGet(url); // url string

        dm.when(() -> {
            try {
                HttpResponse response = client.execute(method); // *** Gets here, then dies on step-over, no error thrown, nothing.

                String result = EntityUtils.toString(response.getEntity(), "UTF-8");
                return result;
            } catch (Exception e) {
                return "frick"; // Never gets here
            }
        }).done(result -> {
            // Do stuff (never gets here)
            // has d.resolve(<stuff>)
        }).fail(error -> {
            // Never gets here either
            // has d.reject(error)
        });

        return p;
    }
```

Appreciate the help.
PS Should I be posting this on SO instead of here?

**Comment by mccannmax** [comment]
Wondering if there's a way to pull that code in via Gradle?
```compile 'com.ning:async-http-client:1.9.5'``` does not appear to pull it into the project.

**Comment by mccannmax** [comment]
Ended up wrapping my own inherited from DeferredAsyncTask
