### ISSUE TITLE
DeferredCallable has different type parameters than Promise/Deferred

### ISSUE THREAD

**Issue by mkollinsmith** [jdeferred/jdeferred#49]
DeferredCallable has type parameters <D, P> while Promises have type parameters <D, F, P> . That means the Deferred in the DeferredCallable has error type "Throwable" instead of a user specified error type.

I'd like to specify my own error type with DeferredCallable. Was this difference intended or is it a TBD? Is there any reason not to add a type parameter for errors in DeferredCallable?

**Comment by saturnism** [comment]
hiya, Java Callables expects user to throw exception when there is an error.  If you want to use your own error types, you can use a Runnable instead.

Cheers,

**Comment by mkollinsmith** [comment]
Ah, makes sense, thanks!
