### ISSUE TITLE
Catching and logging exceptions causes program to not notice.

### ISSUE THREAD

**Issue by nwertzberger** [jdeferred/jdeferred#53]
Hey, when using JDeferred along with a netty-based program, I created a NullPointerException. Unfortunately, the promise i had was never rejected because the deferred object threw a null pointer exception. Here's an example:

    final String str = null;
    deferred.then( () -> otherPromise.resolve(null.size()) );

That nullpointerexception will just be eaten and never keyed off of. The only option i see is to wrap everything in these try {} catch(Exception e){} blocks, but i'd rather be able to have an "except" tag or something to deal with caught exceptions ( for example)

    final String str = null;
    deferred.then( () -> otherPromise.resolve(null.size()) )
        .except((e) -> otherpromise.reject());

**Comment by nwertzberger** [comment]
#54 Is a potential implementation of this.

**Comment by saturnism** [comment]
@nwertzberger if you use callable or runanble directly, it should already handle exceptions and pass them to the fail callback.  Would that be useful?

**Comment by saturnism** [comment]
after thinking through this a bit, it's important that the exception is caught and dealt w/ the by the callbacks, and propagated to the failure handlers.
