### ISSUE TITLE
1.2.4 release to maven central?

### ISSUE THREAD

**Issue by ggggl** [jdeferred/jdeferred#55]
Hi, is there a plan to release v1.2.4 to maven central?  
I am interested in particular in the memory leak fix that was merged in 2ea5d9.  I can pull the source myself, but it would be great to be able to pull in the jar the usual way via my pom file, etc.

Thanks!

**Comment by saturnism** [comment]
Hi,

I will take a look. Thanks!

**Comment by ggggl** [comment]
Hi, 
Just following up to find out if/when this might be accomplished?

Thanks again!

**Comment by saturnism** [comment]
hiya - my bad - 1.2.4 should already be in the repo!
https://maven-repository.com/artifact/org.jdeferred

cheers,

**Comment by saturnism** [comment]
oh wait it's still in staging for some reason :/

**Comment by ggggl** [comment]
Right, cool, I see that - do you know when it might be moved out of staging?

Thanks!

**Comment by saturnism** [comment]
I just re-performed the release - it should be on maven central shortly! Thanks,

**Comment by saturnism** [comment]
it's there now!

https://maven-repository.com/artifact/org.jdeferred

**Comment by ggggl** [comment]
Thanks for looking into it - 
Is there something I am missing though?  Clicking into the 1.2.4 page, I still see the repo URL as https://oss.sonatype.org/content/repositories/staging/org/jdeferred/jdeferred/1.2.4/  

Thanks!

**Comment by saturnism** [comment]
doh! that seems to be exactly wht happened last time... sorry abt that - let me check again!

**Comment by kuc** [comment]
But I can download 1.2.4 from Maven just fine - strange...

**Comment by ggggl** [comment]
It seems to be coming in now, actually - before you tried to re-release I was not finding it, but now I seem to be.  I guess that did work, regardless of the URL I pasted above - 

I guess whatever you did worked
thanks!

**Comment by saturnism** [comment]
=) closing!
