### ISSUE TITLE
Passing non-void parameters to the DeferredAsyncTask

### ISSUE THREAD

**Issue by danielfaust** [jdeferred/jdeferred#58]
I've been trying to replace the
```java
new DeferredAsyncTask<Void, Throwable, Object>
```
with a
```java
class DeferredFlowControl {
    String mURL = "...";
    String mDownloadResult = null;
    String mFilename = "...";
    String mSaveResult = null;
}
final DeferredFlowControl dfcSequence = new DeferredFlowControl();

new DeferredAsyncTask<DeferredFlowControl, Throwable, Object>
```
but I can't find a way to make use of that DeferredFlowControl instance named dfcSequence.

I could make the tasks read/write the variables of the dfcSequence directly, but I'm trying to pass that dfcSecuence around as a parameter, as I can do with normal AsyncTasks, by passing it to the AsyncTask.execute(dfcSequence);

Is it possible to do this? The DeferredAsyncTask never gets to call the doInBackgroundSafe, as a `java.lang.ClassCastException: java.lang.Void[] cannot be cast to .....$1DeferredFlowControl` exception is raised.

**Comment by danielfaust** [comment]
Hmm, from looking at the code, the AndroidDeferredManager in particular, it appears that void is the only possible parameter ( https://github.com/jdeferred/jdeferred/blob/master/android/library/src/main/java/org/jdeferred/android/AndroidDeferredManager.java#L84 ). This seems to be similar to CodeAndMagic's andoird-deferred-object where the DeferredAsyncTask is also called without parameters ( https://github.com/CodeAndMagic/android-deferred-object/blob/master/library/src/main/java/org/codeandmagic/deferredobject/android/DeferredAsyncTask.java#L47 )

**Comment by saturnism** [comment]
Hiya - it is the at the moment.  The idea is to specify the type for the Result, Failure, and Progress types - none of which are argument parameter types.

The idea/pattern doesn't exactly rhyme w/ how Async task takes in the argument params.
