### ISSUE TITLE
Support for array of Callables/Promises on then (Promise.all)

### ISSUE THREAD

**Issue by yaraju** [jdeferred/jdeferred#62]
If we need to assure execution of all callables before calling the next in line, in a pipe, we have to do this:

``` java
final List<Callable<String>> callables = ImmutableList.of(callable1, callable2);

dm.when(doCall1)
  .then(new DonePipe<String, MultipleResults, OneReject, MasterProgress>() {
                    @Override
                    public Promise<MultipleResults, OneReject, MasterProgress> pipeDone(String result) {
                        return dm.when(callables.toArray(new Callable[callables.size()]));
                    }
                })
  .then(new DoneCallback<MultipleResults>() {
                    @Override
                    public void onDone(MultipleResults result) {
                        System.out.println("Now all the callables have finished");
                    }
                });
```

Instead, we should be able to do something like:

``` java
final List<Callable<String>> callables = ImmutableList.of(callable1, callable2);

dm.when(doCall1)
  .then(Promise.all(callables))
  .then(new DoneCallback<List<String>>() {
                    @Override
                    public void onDone(List<String> result) {
                        System.out.println("Now all the callables have finished");
                    }
                });
```

**Comment by saturnism** [comment]
@yaraju have you used dm.when(c1, c2, c3)?  :) it should just work.

See https://github.com/jdeferred/jdeferred/blob/master/core/src/main/java/org/jdeferred/DeferredManager.java#L166

Thanks!

**Comment by saturnism** [comment]
oh my bad, I think I misunderstood the request.  I thnk you are looking for a convenience method that is literally a DonePipe that wraps the dm.when(...) calls for you.

However, that will assume the use of its own DeferredManager, which is not preferable - since you may have your own dm that uses your own executor service.

I'd recommend implementing the wrapper in your specific use case - but share with us what you do - perhaps we can make it more generic.

Thanks!

**Comment by yaraju** [comment]
@saturnism Yes, I did mean a convenience method for a DonePipe. In ES6-promises, you can chain then() any number of times, forming a pipe.

After some attempts, I realized my snippet wouldn't actually pass on any data to the next function in the then() chain, making it not so useful.

For my purpose, I just went ahead with using a List<FutureTask> and doing a looped "get" on all of them before continuing operations - so that code wouldn't be very useful for a proper chaining.

I did start writing an ES6 based Promise library, but couldn't finish testing it. Will link to it if/when I get to pushing it to Github(which I plan to)

**Comment by NomNuggetNom** [comment]
I'd love this feature too. I love ES6's syntax for this.

**Comment by saturnism** [comment]
we added "settle" semantics in #118 ptal!

**Comment by saturnism** [comment]
but, you'll still need to wrap w/ a DonePipe. At the moment I don't see a clean way to provide convenience method to create the DonePipe itself.  Thanks!
