### ISSUE TITLE
Is AndroidDeferredManager always return MultipleResults in the same order?

### ISSUE THREAD

**Issue by ariefbayu** [jdeferred/jdeferred#63]
I just need confirmation, from the following snippets:

	findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
	    @Override
	    public void onClick(View view) {
	        AndroidDeferredManager androidDeferredManager = new AndroidDeferredManager();
	        androidDeferredManager
	                .when(new Callable<Object>() {
	                            @Override
	                            public String call() throws Exception {
	                                Thread.sleep(3000);
	                                return "Hello World 1!";
	                            }
	                        },
	                        new Callable<Object>() {
	                            @Override
	                            public String call() throws Exception {
	                                Thread.sleep(2000);
	                                return "Hello World 2!";
	                            }
	                        },
	                        new Callable<Object>() {
	                            @Override
	                            public String call() throws Exception {
	                                Thread.sleep(1000);
	                                return "Hello World 3!";
	                            }
	                        },
	                        new Callable<Object>() {
	                            @Override
	                            public String call() throws Exception {
	                                Thread.sleep(1900);
	                                return "Hello World 4!";
	                            }
	                        })
	        .done(new DoneCallback<MultipleResults>() {
	            @Override
	            public void onDone(MultipleResults result) {
	                for(OneResult res: result){
	                    Log.d("LOG", "Result: " + res.toString());
	                }
	            }
	        });
	    }
	});

I saw the following logs:

    08-11 11:21:57.853    6234-6234/id.flwi.deferredtesting D/LOG﹕ Result: OneResult [index=0, promise=org.jdeferred.android.AndroidDeferredObject@533e7b78, result=Hello World 1!]
    08-11 11:21:57.853    6234-6234/id.flwi.deferredtesting D/LOG﹕ Result: OneResult [index=1, promise=org.jdeferred.android.AndroidDeferredObject@533e990c, result=Hello World 2!]
    08-11 11:21:57.853    6234-6234/id.flwi.deferredtesting D/LOG﹕ Result: OneResult [index=2, promise=org.jdeferred.android.AndroidDeferredObject@533e9a94, result=Hello World 3!]
    08-11 11:21:57.853    6234-6234/id.flwi.deferredtesting D/LOG﹕ Result: OneResult [index=3, promise=org.jdeferred.android.AndroidDeferredObject@533e9c28, result=Hello World 4!]

Result is always in that order. So again, Is `MultipleResults` always came in the same order?

**Comment by saturnism** [comment]
Hiya,

Current implementation seems to be in the same order - but it should never be assumed in an async system.
