### ISSUE TITLE
Make jdeferred-android.jar available

### ISSUE THREAD

**Issue by capellsk** [jdeferred/jdeferred#66]
While jdeferred-core.jar is available on Maven, jdeferred-android.jar is not (apklib, etc are there), and there seems to be no other distribution repository. This creates a high barrier to use for those people who don't use Maven.

A related problem is that it's not documented which libraries are needed for an Android App:
jdeferred-core
jdeferred-android
slf4j-api (this one is hard to guess from the myriad libraries for slf4j)
slf4j-android

**Comment by saturnism** [comment]
hiya - I thought the jdeferred-android jar is already available on maven central.  in addition to group, artifact, version, have you also specified the type?

http://jdeferred.org/

Thanks!

**Comment by capellsk** [comment]
Hi Ray,

I don't see it.

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jdeferred-android%22

Thanks,
Steve

**Comment by saturnism** [comment]
Ah, I know what you mean. You are right that jdeferred-android.jar isn't available, but if you are building an android app, won't you be able to use either the apklib or the aar archives?

i think i can build the lib as a jar without any resources, etc.  will give it a try, but contribution are welcome!

**Comment by capellsk** [comment]
I'm relatively new to Android development, but as far as I could figure
out, APKLIB and AAR are not supported by Eclipse without jumping through a
lot of hoops. I followed some advice to unzip the APKLIB and make a library
out of it but I couldn't get it working. Apparently there is a Maven plugin
for Eclipse that allows you to use APKLIB, but for someone who isn't
already using Maven it's unclear if that magically lets you use the APKLIB
or forces you through some Maven pipeline you're not familiar with. Anyway,
all that is a lot of hassle compared to dropping in a JAR the old-fashioned
way.  :)

**Comment by saturnism** [comment]
hiya! i haven't forgotten this yet. i think what i can do is in the `android` modules, create `library-apk`, `library-aar`, and then just `library` that produces the jar file. I'm not 100% sure if that'll work out of the box like that though.

**Comment by saturnism** [comment]
@aalmiray fyi - i think we can also produce jdeferred-android.jar in addition to aar and apklib.

**Comment by saturnism** [comment]
closed by #89

**Comment by capellsk** [comment]
Thanks!
