### ISSUE TITLE
waitSafely - why does this work?

### ISSUE THREAD

**Issue by FreakTheMighty** [jdeferred/jdeferred#67]
I opened a question on [StackOverflow](http://stackoverflow.com/questions/33397245/android-instrumentation-run-failed-assertion-error) and have found a solution, but I don't fully understand why it works. The solution appears related to jdeferred, so I thought you might be able to shed light on it.

I am using `waitSafely` to test code that is run in a thread. My broken code looked like this:

```
    Promise prom = client.find(new VideoQueue())
            .set("user", "212139")
            .run()
            .done(new DoneCallback<ArrayList<VideoQueue>>() {
                @Override
                public void onDone(ArrayList<VideoQueue>  videoQueue) {
                    assertNotNull(videoQueue);
                    assertNotNull(videoQueue.get(0));
                    assertNotNull(videoQueue.get(0).getId());
                    assertEquals("3310190", videoQueue.get(0).getId());
                }
            }).fail(new FailCallback() {
                @Override
                public void onFail(Object rejection) {
                    assertNull(rejection);
                }
            });

    prom.waitSafely();
```
The result was that the test runner would fully exit when an assertion failed. After moving `waitSafely` before `done`, the issue has resolved itself. The assertion fails, but the runner continues through the other tests. The code below works.
```
        Promise prom = client.find(new VideoQueue())
                .set("user", "212139")
                .run();

        prom.waitSafely();

        prom.done(new DoneCallback<ArrayList<VideoQueue>>() {
                    @Override
                    public void onDone(ArrayList<VideoQueue>  videoQueue) {
                        assertNotNull(videoQueue);
                        assertNotNull(videoQueue.get(0));
                        assertNotNull(videoQueue.get(0).getId());
                        assertEquals("3310190", videoQueue.get(0).getId());
                    }
                }).fail(new FailCallback() {
                    @Override
                    public void onFail(Object rejection) {
                        fail();
                    }
                });
```

Do you have any insight into why this change works?

**Comment by saturnism** [comment]
Hiya,

First of all, asserting in the callback probably won't work as expected.  You almost have to store state in a higher level atomic holder (see the JDeferred tests for examples), and then assert based on the holder value.

E.g., if you want to assert something failed, you should:
1. initialize AtomicBoolean failed` to `false` outside of the callbacks
1. in the onFail callback, set an `AtomicBoolean failed` to hold `true`
1. after `waitSafely`, assert on the value held inside of the `failed` variable

I'd start with that - thanks!

**Comment by FreakTheMighty** [comment]
Thanks for the tip. There definitely was some weirdness with the asserts in the callback, however, my latest change seems to work even while keeping them where they are. In one variation, I tried something similar to what you are describing, I moved the variables I was asserting outside of the callback. It did work, but it complicated my test design.

Anyways, thanks for your thoughts.

**Comment by nwertzberger** [comment]
Hey,

I've got a fix for this so it just throws whatever throwable you had once you call .wait() or .waitSafely().

**Comment by saturnism** [comment]
@nwertzberger would be very much like to see the updates! thanks!

**Comment by nwertzberger** [comment]
I have a pull request for this.
