### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [jdeferred/jdeferred#73]
Hi
The following source files are without license headers:
./android/test/src/main/java/org/jdeferred/android/test/AndroidDeferredManagerTest.java
./android/test/src/main/java/org/jdeferred/android/test/MainActivity.java

./core/src/main/java/org/jdeferred/DeferredRunnable.java
./core/src/main/java/org/jdeferred/DeferredCallable.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by saturnism** [comment]
Thanks for the note - yes these files are all Apache 2.0 licensed. I'll fix this.

**Comment by Anix-PasBesoin** [comment]
Has this bug been fixed?

**Comment by puntogil** [comment]
NO

**Comment by aalmiray** [comment]
It's fixed with #89. Pending review by @saturnism

**Comment by saturnism** [comment]
Will get on this!

**Comment by saturnism** [comment]
Closed by #89
