### ISSUE TITLE
jdeferred-android-aar is missing android directory

### ISSUE THREAD

**Issue by kykrueger** [jdeferred/jdeferred#78]
When using 'org.jdeferred:jdeferred-android-aar:1.2.4', I cannot make includes to files in the android directory. 

For example, the AndroidDeferredObject is not found. I have a workaround in place that takes the source code from this library and includes it in my project, but it would be ideal to just use the aar dependency.

Any idea how this could happen, and is this library still being supported?

**Comment by saturnism** [comment]
that's interesting - the AAR is here: https://mvnrepository.com/artifact/org.jdeferred/jdeferred-android-aar/1.2.4

Do you know if including APKLIB would work better?
https://mvnrepository.com/artifact/org.jdeferred/jdeferred-android/1.2.4

Thanks,

**Comment by saturnism** [comment]
if this was in fact an issue, it should also've been fixed by #89

**Comment by kykrueger** [comment]
Sorry, I had missed the last update to this issue. 
There was a workaround I had done for the problem by downloading the source code and including it in my project. 
I will check if that is still necessary in 1.2.5, is it released now?

**Comment by kykrueger** [comment]
Also, it looks like the APKlib would have also worked as a fix. It seems to include the missing files in the android directory.
