### ISSUE TITLE
Can't import some classes in the 1.2.5 release

### ISSUE THREAD

**Issue by Gloix** [jdeferred/jdeferred#97]
I imported the gradle dependency in its version 1.2.5 and tried to declare a `Deferred` object, but Android Studio couldn't import the proper class. I tried the jar and aar versions but none of them seemed to work. I then used version 1.2.4 and now I get the `Deferred` class imported properly.

Note however that I could import the `DeferredAsyncTask` class, however the main types are not visible.

**Comment by aalmiray** [comment]
Which dependencies did you define for 1.2.5? AFAIK IntelliJ (Android Studio anyway) should show dependencies on the project explorer (left sidebar) allowing you to look inside the JAR files. Are you able to sot the `Deferred` class inside the JARs?

**Comment by Gloix** [comment]
By importing with `compile 'org.jdeferred:jdeferred-android-aar:1.2.5'` or `compile 'org.jdeferred:jdeferred-android-aar:1.2.5@aar'`:
![image](https://cloud.githubusercontent.com/assets/5000394/22977365/225bd1b2-f36d-11e6-9bbc-eb923af1f160.png)

By importing version 1.2.4 with `compile 'org.jdeferred:jdeferred-android-aar:1.2.4'`
![image](https://cloud.githubusercontent.com/assets/5000394/22977605/14be595c-f36e-11e6-98fb-4020ca393014.png)

It seems the core of jdeferred is not added to the dependencies list in version 1.2.5.

**Comment by aalmiray** [comment]
I see. The pom for jdeferrrd-android-aar does not define any dependencies at all. @saturnism there's a commented section found in the subprojects build file (lines 157 - 163) that should do the trick. 

In the meantime, a workaround is to explicitly add a dependency to jdeferred-core-1.2.5 to your build file.

**Comment by saturnism** [comment]
@aalmiray ptal at the PR. Thanks @Gloix for spotting this.
